server/documents/collections/form.html.eco
Current version does not work, as it selects a `select` element, which is not even part of the dropdown html.
Note: I did not test this with Fomantic, just resubmitting https://github.com/Semantic-Org/Semantic-UI-Docs/pull/407 here, as I have heard this is the new thing! :smile:
=> Fix form dropdown js example code

README.md, server/documents/cla.html.eco, server/documents/collections/grid.html.eco, server/documents/elements/container.html.eco, server/documents/elements/icon.html.eco, server/documents/elements/image.html.eco, server/documents/globals/reset.html.eco, server/documents/globals/site.html.eco, server/documents/index.html.eco, server/documents/introduction/advanced-usage.html.eco, server/documents/introduction/build-tools.html.eco, server/documents/introduction/getting-started.html.eco, server/documents/introduction/glossary.html.eco, server/documents/introduction/integrations.html.eco, server/documents/modules/nag.html.eco, server/documents/modules/popup.html.eco, server/documents/modules/tab.html.eco, server/documents/usage/layout.html.eco, server/documents/views/card.html.eco, server/files/stylesheets/library/basic.icon.css
Reverted to Semantic for Links to Repos (Components, Angular,React,Ember, Gulp-Example...) which are currently not in scope for fomantic or only exists in semantic-org
=> Changed Semantic to Fomantic at related places. 

server/files/javascript/docs.js, server/partials/library-javascript.html.eco
As the html code for the adblock was removed by #40 , the related JS code should be removed aswell to avoid js errors.
I just commented it out for now. Who knows if it might be of interested later
=> Disable Adblock code, dont even include the library

server/documents/modules/popup.html.eco
Added new tooltip sizes and basic example as of https://github.com/fomantic/Fomantic-UI/pull/202
=> [Popup] Added new tooltip sizes and basic example

server/documents/collections/form.html.eco
The Radiobutton grouping example had all radiobuttons given the same name, so they technically belong to the same group, but the example suggested to have 2 different groups instead
https://github.com/Semantic-Org/Semantic-UI/issues/6681
=> [Form] Separate Radio buttons to their groups

server/documents/modules/toast.html.eco
Docs changed according to https://github.com/fomantic/Fomantic-UI/pull/178
Simplifies usage with `ui message` and follows the naming standard of  sui for titles/headers
=> [Toast] className title to header

server/documents/elements/input.html.eco
Added Examples of Corner Labels and icon within `textarea`-tag  when using the `input`
https://github.com/fomantic/Fomantic-UI/pull/277
=> [Input, Textarea] Examples for corner labels and icons

server/documents/collections/table.html.eco
Once https://github.com/fomantic/Fomantic-UI/pull/261 will me merged, the tables automatically get the possibility to also use the central colors on cells and rows
=> [Table] Cell colors support Example

server/documents/behaviors/api.html.eco
While talking in the SUI gitter channel, we came across a question if it's possible to implement a feature of having a central url being attached to all action urls at once.
After a while i found out this feature is already part of the API behaviour by using the `base` option...it is just not documented :disappointed: 
..so i added this option to the API docs
=> [API] Added undocumented base-parameter

server/documents/introduction/new.html.eco, server/files/javascript/docs.js
* Add active tab name (e.g. New in 2.x) in toc, not only in the page but also globally.
* If no tabs menu on the page, it is just skipped.
* Change page title of `new.html` to `What's New`.
#68.
=> Style: ToC include active tab name

server/documents/elements/label.html.eco
Follow-up of https://github.com/fomantic/Fomantic-UI/pull/388
=> [Label] Right icon should have correct margin when placed after text

server/documents/modules/dropdown.html.eco, server/documents/modules/search.html.eco
Added examples for dropdown and search option `ignoreDiacritics`  as of https://github.com/fomantic/Fomantic-UI/pull/422
=> [Dropdown,Search] Added examples for dropdown and search option 'ignoreDiacritics' 

server/documents/elements/segment.html.eco
Added new "stackable horizontal segments" example as of https://github.com/fomantic/Fomantic-UI/pull/398
=> [Segment] Added new "stackable horizontal segments" example

server/documents/elements/label.html.eco
Added `bottom floating label` example according to https://github.com/fomantic/Fomantic-UI/pull/430
=> [Label] Added bottom floating label example

server/documents/collections/table.html.eco, server/documents/modules/popup.html.eco, server/documents/views/card.html.eco, server/partials/examples/card.html, server/partials/examples/popup.html, server/partials/examples/rating.html
Several parts of the docs, where a rating element was used, still had the old syntax resulting in always displaying a black star
=> [Rating] Fixed all examples of rating to use the new syntax

server/files/javascript/icon.js
Alias search allows users to search icons in other name.
Aliases are stored in `data-search-terms` attribute in `icons.html.eco` which is generated by icon-script. See the related PR 
* https://github.com/fomantic/icon-script/pull/5
* https://github.com/fomantic/icon-script/pull/6
This PR does NOT include changes in `server/documents/elements/icon.html.eco` (`data-search-terms`) intentionally (see https://github.com/fomantic/Fomantic-UI-Docs/pull/67#issuecomment-451013371). 
So icon search works fine but alias search do not.
Aliases are shown in grey text as description of Search module.
https://github.com/Semantic-Org/Semantic-UI/issues/6313
=> Feat: Icon alias search

server/documents/collections/grid.html.eco
The example for Device visibility accidently assigned the `large screen` class to the `widescreen` example row. Thus both were always displayed together,although `widescreen` should only be displayed when the viewport sizes reached HD 1920 width
https://fomantic-ui.com/collections/grid.html#device-visibility
=> [Grid] Widescreen example was defined as large screen

server/documents/modules/modal.html.eco
OPtions `inverted`, `blurring` and `centered` were not documented on the modals settings page. Added them
https://github.com/fomantic/Fomantic-UI/issues/515
=> [Modal] Missing settings documented

server/documents/modules/modal.html.eco
Added Example for `overlay fullscreen modal` as of https://github.com/fomantic/Fomantic-UI/pull/526
=> [Modal] overlay fullscreen modal example

server/documents/modules/modal.html.eco
The new overlay fullscreen example was also opened when the normal fullscreen example was called 🙄
=> [Modal] Normal fullscreen example was opening new overlay example aswell

server/documents/modules/calendar.html.eco, server/files/javascript/calendar.js
- Added Examples and settings for shortyear calculation and enabledDates option
- Fixed custom date format example not working
https://github.com/fomantic/Fomantic-UI/pull/527
https://github.com/fomantic/Fomantic-UI/pull/525
=> [Calendar] Examples and settings for shortyear calculation and enabledDates option

server/documents/usage/theming.html.eco
The color on the docs describing the red color as hex number was wrong.
=> Fixed wrong red color on the hex description

server/documents/modules/calendar.html.eco
Added the new `weekCell` classname
> According to the related PR, the default name is still `disabled` to keep previous behavior. Just in case you might think it's a copy/paste issue 😉 
https://github.com/fomantic/Fomantic-UI/pull/560
=> [Calendar] Added weekCell setting

server/documents/modules/dropdown.html.eco
Add new content for columnar dropdown proposed in https://github.com/fomantic/Fomantic-UI/pull/586
=> [Dropdown] Add examples of columnar dropdown menu.

server/documents/modules/calendar.html.eco
Added `selectAdjacentDays` example and setting as of https://github.com/fomantic/Fomantic-UI/pull/562
=> [Calendar] Added 'selectAdjacentDays' example and setting

server/documents/modules/dropdown.html.eco
The function `determine intent` was renamed to `determine eventInModule` (by f56d41575ab01b20869c0cba0fb3890fa5260d39 and finally by f2d7d0c2446485d540b07b1d70154419bd1d34b6)in 2014, but never updated in the docs. This PR does it now
https://github.com/Semantic-Org/Semantic-UI/issues/3540
=> [Dropdown] Corrected old renamed behavior

server/documents/modules/calendar.html.eco
Added examples for eventDates and settings for onSelect callback as of https://github.com/fomantic/Fomantic-UI/pull/677
=> feat(calendar): add eventDates examples and onSelect callback setting

server/documents/modules/dropdown.html.eco
One example for bottom pointing menu was off canvas on mobile
https://github.com/Semantic-Org/Semantic-UI/issues/5415
=> fix(dropdown): bottom pointing example didn't show on mobile

server/documents/modules/modal.html.eco
The example using the inverted dimmer variant showed 2 modals instead of one
http://fomantic-ui.com/modules/modal.html#dimmer-variations
=> fix(modal): inverted dimmer example showed two modals

server/documents/modules/calendar.html.eco
A closing brace was missing in the example for formatter setting
https://github.com/fomantic/Fomantic-UI/issues/621
=> fix(calendar): missing closing brace in formatter example

server/documents/elements/reveal.html.eco
The example for `move right reveal` was not hiding the "visible item" image when it moves away.
The dimensions were not set, so the div occupied the whole width which made the overflow: hidden (from reveal) usesless
https://fomantic-ui.com/elements/reveal.html
https://jsfiddle.net/moLtk1nx/
|Before|After|
|-|-|
|![reveal_before](https://user-images.githubusercontent.com/18379884/56662751-f6a21d80-66a4-11e9-8159-94aea2c6e99e.gif)|![reveal_after](https://user-images.githubusercontent.com/18379884/56662761-fb66d180-66a4-11e9-814f-2285064bb2aa.gif)|
https://github.com/fomantic/Fomantic-UI/issues/689
=> [Reveal] right move was not bound to image dimensions so overflow:hidden was useless

server/files/javascript/docs.js, server/files/stylesheets/docs.css
Example headers have hidden anchor that are available through TOC.
I frequently share the URLs of example to example with team.
To get URL, we need to click TOC.
I think it is more intuitive to click header itself to get URL.
And these headers have no visual appeal to indicate they have anchors.
So this PR 
* Adds `linkify` icon as visual appeal to example headers
* Make headers itself clickable so users can get URL to headers
=> feat(*): make headers visible anchors

server/files/stylesheets/docs.css
The new searchbar on the frontpage gets invisible when the page is scrolled and the menu gets a white background
=> fix(index): search wasn't visible when fixed at top while scrolling

server/documents/modules/progress.html.eco
I corrected wrong default values in progress settings.
=> [Progress] Correct wrong default values

server/documents/modules/progress.html.eco, server/files/javascript/progress.js
Added examples for the new indeterminate progress features as of https://github.com/fomantic/Fomantic-UI/pull/735
=> feat(progress): add indeterminate examples

server/documents/usage/theming.html.eco
Without these, the build fails and the error isn't very intuitive (e.g. `Recursive variable definition for @toast`) so will trip newcomers up.
=> Add required variables to example theme.config

server/documents/modules/calendar.html.eco
A small typo fix in calendar settings (`Fisable` -> `Disable`)
https://github.com/fomantic/Fomantic-UI/issues/835
=> [Calendar] Typo Fix

server/documents/behaviors/form.html.eco
Sometimes it's written as id or ID or IDS, but an id in JavaScript is `#id`, while an identifier for form validation can be either an `id`, `name` or `data-validate` value. To avoid confusing let's keep it all the same as how it's introduced in the beginning.
I'm I right that fieldName is actually limited to a `name` value? It's not easy to decipher that from the code...
=> [Form Validation] Be consistent with 'identifier' naming

server/documents/collections/message.html.eco
A paragraph in mesage was missing the closing tag
Adopted from https://github.com/Semantic-Org/Semantic-UI-Docs/pull/386
Thanks to @hisener
=> fix(message): Missing closing tag

server/documents/behaviors/api.html.eco
Adjusted missing callback parameters to server response example to match with settings entry and actual codebase
Adopted from https://github.com/Semantic-Org/Semantic-UI-Docs/pull/413
Thanks to @daveharris
=> fix(api): added missing callback parameters in response example

server/documents/collections/form.html.eco
Double `##` lead into non working anchor link
Adopted from https://github.com/Semantic-Org/Semantic-UI-Docs/pull/423
Thanks to @mtsanaissi
=> fix(form): Corrected anchor link to dropdown multiple reference

server/documents/modules/slider.html.eco
In Settings tabs of Slider Module, the header title its "Calendar"
=> Misswriting on dividing header

server/documents/behaviors/visibility.html.eco
Infinite scroll should only ever be at the bottom of a page.
Having it at the top causes a bad experience and for users/developers to be unable to read through the other examples, particularly the Image LazyLoad as the infinite scroll is so aggressive.
In addition  this PR fixes a wrong closing tag.
Adopted from https://github.com/Semantic-Org/Semantic-UI-Docs/pull/394
Thanks to @kenman345
=> fix(visibility): Moved inifinite scroll to end of page for better usability and fixed wrong closing tag

server/documents/modules/calendar.html.eco
Change infos to new `onBeforeChange` and old `onChange` callback as of  https://github.com/fomantic/Fomantic-UI/pull/982
> I added a prominent red exclamation mark because this is a breaking change (Users have to change their current onChange usages to onBeforeChange to gain the same effect as before
=> [Calendar] Infos for new onBeforeChange andold onChange callbacks

server/documents/modules/calendar.html.eco, server/files/javascript/calendar.js
Added one example for usage of type and date as metadata 
https://github.com/fomantic/Fomantic-UI/pull/1093
=> [Calendar] type and date as data attributes example

server/documents/modules/calendar.html.eco
Added missing `append` selector, which was invented by https://github.com/fomantic/Fomantic-UI/pull/752 ,  and a short info about its usage
https://github.com/fomantic/Fomantic-UI/issues/1146
=> feat(calendar): added missing append selector and short info about usage

server/documents/modules/slider.html.eco
added undocumented interpretLabel example and setting explanation
#170
=> feat(slider): add interpretLabel example and setting example setting

server/documents/modules/popup.html.eco
The popup example with predefeined HTML missed the rating star icons
#185
=> fix(popup): star icons were missing in predefinded html example

server/documents/modules/dropdown.html.eco
Added example how to preserve `data-text` on `select` dropdown conversions as of https://github.com/fomantic/Fomantic-UI/pull/1219
=> [Dropdown] added example for data-text preserve on select conversion

server/documents/modules/modal.html.eco
Added info about the optional `inside` class for the close icon of modals according to https://github.com/fomantic/Fomantic-UI/pull/1215
=> [Modal] Added info about "inside" class for close icons

server/documents/modules/popup.html.eco
Added info about the popup width class `fixed` as of https://github.com/fomantic/Fomantic-UI/pull/1216
=> [Popup] Added info about "fixed" class for popup widths

server/documents/modules/dropdown.html.eco
Added an example for the `unfilterable item` feature as of https://github.com/fomantic/Fomantic-UI/pull/1229
=> [Dropdown] Added example for unfilterable items

server/documents/collections/grid.html.eco
Grid alignment example have wrong class set for container, so originally it looked like this:
=> Fixed example for grid alignment

server/documents/elements/segment.html.eco
The `vertical segment` example won't work anymore when  https://github.com/fomantic/Fomantic-UI/pull/1416 will be applied.
Basically the current example is , even without the mentioned PR, only working by accident. whenever an additional div would have been added underneath the vertical segment it wouldnt have worked anymore also.
This PR just wraps the example segments into a separate div, so the `first-child` selector will correctly work (and remove the most upper border again)
Visually this PR otherwise does not make any difference at all.
=> fix(segment): wrap vertical segment example into a separate div to make first-child work

server/documents/modules/rating.html.eco
This PR adds an example for using the rating module as a pure CSS only element, when no interaction is desired, thus no javascript is needed.
=> feat(rating): added example without using javascript

server/raw/jsfiddle/index.html
jsfiddle.net recently removed the feature to append a `/show` to any jsfiddle , which was then only showing the result of a jsfiddle. That was a very handy feature to review/test on mobile devices.
The only possibility now is to embed the jsfiddle into an iframe.
That said, this PR offers a little page which will display the result of any given jsfiddle in an iframe.
Maybe i was too lazy, but i could not find another public service which does just that.
I am aware, that codepen.io still offers that feature somehow by using `/full` instead of `/pen` in their URLs, but as we are using jsfiddle so much often i thought it's a good idea to still have this for jsfiddle as well.
However, i would still only use this when testing on a mobile device is necessary. 
Just append the jsfiddle code to a …
=> feat(chore): added testing page for jsfiddle fullscreen

server/documents/modules/checkbox.html.eco
Disabled checkbox has the same description as read-only checkbox
Copying descriptions for snippets saw this 😄.
P.S. Correct folder? 🙄
=> fix(checkbox) Changed disabled description

server/documents/behaviors/form.html.eco
Added behavior adjustments as of
https://github.com/fomantic/Fomantic-UI/pull/1611
https://github.com/fomantic/Fomantic-UI/pull/1615
`add prompt` was declared twice.
=> feat(form): adjusted behaviors

server/documents/modules/dropdown.html.eco
Added example for the optional `vertical item` of a dropdown description entry as of https://github.com/fomantic/Fomantic-UI/pull/1116
=> [Dropdown] vertical item example

server/documents/introduction/getting-started.html.eco
closes #227 
note: i couldn't build the docs to check because of #192 , so if someone with a working build system wants to check, they can, thank you!
=> fix(getting-started): script tag src and link tag href are incorrect

server/raw/jsfiddle/index.html
While the jsfiddle codes do only consist of numbers and characters, a possible given jsfiddle username infront of the jsfiddle link may contain dashes or underscores, which where removed and thus makes given jsfiddle links not working anymore
=> fix(jsfiddle): support dashes and underscores in jsfiddle usernames

server/documents/elements/input.html.eco
Fix the typo error `aswell` which should be `as well`.
=> fix(input): typo error

server/documents/modules/slider.html.eco
Add the bottom aligned label example ([Fomantic-UI/pull/1631](https://github.com/fomantic/Fomantic-UI/pull/1631)).
=> feat(slider): bottom aligned label

server/documents/modules/dropdown.html.eco
The child combinator syntax `>` is encoded in the example of selector settings and it's not readable for the user. The syntax is encoded into HTML character as `&gt;` because the example code block is formatted as HTML code block via `data-type=html`.
The selector settings is for CSS and so it's formatted as CSS code block by changing `data-type=css`.
**Before:**
**After:**
=> fix(dropdown): incorrect format in example code of selector settings

server/documents/modules/calendar.html.eco, server/files/javascript/calendar.js
Some calendar demo examples are using date arguments for Year, Month and Day separately which is confusing to read. This PR improves the readability of calendar example using an only date string argument instead of three arguments.
Demo presentation with wrong dates.
- https://fomantic-ui.com/modules/calendar.html#single-dates
- https://fomantic-ui.com/modules/calendar.html#enable-only-specific-dates
- https://fomantic-ui.com/modules/calendar.html#event-dates
The calendars looks presenting one month ahead because the month index starts from `0` while passing as month argument. It's correct as usage, but confusing while reading.
=> fix(calendar): improve readability with single date string argument in calendar demo examples

server/documents/behaviors/form.html.eco
- `shouldTrim` per rule
- decimal and number ranges
- minValue and maxValue
as of
https://github.com/fomantic/Fomantic-UI/pull/1814
https://github.com/fomantic/Fomantic-UI/pull/1796
=> feat(form): shouldTrim, maxvalue, minvalue, decimal and number range

server/documents/views/card.html.eco
`disabled` and `loading` state examples as of https://github.com/fomantic/Fomantic-UI/pull/1762
=> feat(card): disabled and loading card examples

server/documents/modules/dropdown.html.eco
Example for `inverted menu` in non-inverted dropdowns as of https://github.com/fomantic/Fomantic-UI/pull/1793
=> feat(dropdown): inverted menu in non inverted dropdown example

server/documents/modules/calendar.html.eco
Added examples for disabled months and years feature as of https://github.com/fomantic/Fomantic-UI/pull/1330
As this feature is already available since 2.8.4 (but we missed to add docs for it since then) the black label says it's new since 2.8.4 (instead of 2.8.8)
> Hint for reviewers: The screenshot has a typo (missing "disable" in "It's possible to ..."), because i created the video gif before i fixed the typo.
> When you look at the changed source the text is fixed saying "It's possible to disable ...."
=> feat(calendar): disabled month and years example

server/documents/collections/message.html.eco
Added `center aligned` and `right aligned` examples to the `message` component as of https://github.com/fomantic/Fomantic-UI/pull/1800
=> feat(message): center and right aligned example

server/documents/modules/modal.html.eco
Example of `center aligned` header/content/actions as of https://github.com/fomantic/Fomantic-UI/pull/1775
=> feat(modal): center aligned variant example

server/documents/modules/toast.html.eco
Added examples for `horizontal` variant as well as for the new possible templates usage as of https://github.com/fomantic/Fomantic-UI/pull/1773
=> feat(toast): added template and horizontal example

server/documents/modules/toast.html.eco
Added examples for `attached` and `centered` variants as of https://github.com/fomantic/Fomantic-UI/pull/1805
=> feat(toast): attached and center aligned examples

server/documents/modules/toast.html.eco
This PR adds a general html layout info as discussed in https://github.com/fomantic/Fomantic-UI/issues/1370#issuecomment-604380107 and added missing context setting as discussed in 
https://github.com/fomantic/Fomantic-UI/issues/1370#issuecomment-600567713 as well as some missing markup
=> feat(toast): added html layout info and context setting 

server/documents/modules/dropdown.html.eco
The example for `remoteData` was missing a comma meaning the sample would not work without spotting it
Also added missing behaviour `get query`
=> fix(dropdown) Fixes remoteData example and adds missing behaviour

server/documents/elements/icon.html.eco
Examples for new variations `circular colored` and `bordered colored` of the `icon` component as of https://github.com/fomantic/Fomantic-UI/pull/1856
=> feat(icon): colored bordered circular examples

server/documents/modules/dropdown.html.eco
Example of optional `description` and `descriptionVertical` item values setting as of https://github.com/fomantic/Fomantic-UI/pull/1852
=> feat(dropdown): vertical description values example

server/documents/elements/container.html.eco, server/documents/elements/emoji.html.eco, server/documents/elements/icon.html.eco, server/documents/elements/label.html.eco, server/documents/elements/rail.html.eco, server/documents/elements/reveal.html.eco, server/documents/elements/step.html.eco
- `elements/container`
- `elements/emoji`
- `elements/icon`
- `elements/label`
- `elements/rail`
- `elements/reveal`
- `elements/step`
=> chore(elements): fix typo

server/documents/modules/checkbox.html.eco, server/documents/modules/embed.html.eco, server/documents/modules/nag.html.eco, server/documents/modules/search.html.eco, server/documents/modules/shape.html.eco, server/documents/modules/tab.html.eco, server/documents/modules/toast.html.eco, server/documents/modules/transition.html.eco
- `modules/checkbox`
- `modules/embed`
- `modules/nag`
- `modules/search`
- `modules/shape`
- `modules/tab`
- `modules/toast`
- `modules/transition`
=> chore(modules): fix typo

server/documents/modules/search.html.eco
The `cancel request` behavior was documented twice.
#273
=> fix(search): cancel query behavior exists twice

server/documents/collections/menu.html.eco
Added an example for `disabled item`
=> fix(menu): added disabled example

server/documents/elements/segment.html.eco
Added an example for the new `horizontal equal width segements` variation as of https://github.com/fomantic/Fomantic-UI/pull/1969
=> feat(segment): added horizontal equal width example

server/documents/modules/dimmer.html.eco, server/documents/modules/dropdown.html.eco, server/documents/modules/modal.html.eco, server/documents/modules/popup.html.eco
Added settings info for the new unique transition syntax for individual show/hide methods/duration in dimmer, modal, popup and dropdown as of
https://github.com/fomantic/Fomantic-UI/pull/1867
https://github.com/fomantic/Fomantic-UI/pull/1869
https://github.com/fomantic/Fomantic-UI/pull/1966
https://github.com/fomantic/Fomantic-UI/pull/1974
=> feat(dimmer,dropdown,modal,popup): individual show/hide transition

server/partials/footer.html
codefund.io is offline / dead and the js tracker is not resolvable anymore. Even the github repo is archived.
=> fix(footer): codefund is no more

server/files/javascript/docs.js
Whenever a link to the docs contains a anchorpoint starting with a "#/" in the URL (used by the tab history plugin) this let into a console error, because jquery is not able to retrieve a matching element (runs into a console error itself)
Additionally when a non existing anchor was given the whole docs script broke
#135
=> fix(chore): slashes in anchorpoints let into console error

server/documents/modules/modal.html.eco
I finally found time to prepare the docs for the new dynamic modal and JS config templates feature 🙂 
as of 
https://github.com/fomantic/Fomantic-UI/pull/1869
https://github.com/fomantic/Fomantic-UI/pull/1774
=> feat(modal): dynamic and js template examples and settings

server/documents/modules/toast.html.eco
The new HTML Layout info of the toast DOM nodes broke all toast examples which didn't have a `position` setting.
The DOM info was accidently used by the toast container itself.
By removing the position info from the layout info, this is fixed in the docs.
=> fix(toast): container html info broke examples

server/documents/modules/calendar.html.eco
Safaris Date() implementation does not support short 1 digit notations of month and day when converting from a string. Thus all related examples using this format are broken in Safari.
Try this on Safari 
https://jsfiddle.net/lubber/9kp6dc1r/1/
https://jsfiddle.net/lubber/9kp6dc1r/2/
#290
=> fix(calendar): 2 digits date notation for safari support

server/documents/behaviors/form.html.eco
Since 2.8.8, it is possible to mix short and longhand notation in validation rule objects as of https://github.com/fomantic/Fomantic-UI/pull/1810 .
This was missed to be added to the docs, so here it is.
=> fix(validation): mix short and longhand notation possible since 2.8.8

server/documents/modules/calendar.html.eco
With the removal of superfluous event listeners on the calendar module, the popup will not act as described before. To reflect the docs better, the calendar module should be triggered by click events by default.
This reflects the changes done in fomantic/Fomantic-UI#1439, fomantic/Fomantic-UI#1508 and fomantic/Fomantic-UI#1509
=> fix(calendar): reflect the changes to the calendar module

server/documents/elements/flag.html.eco
The original PR for the new svg flags was supposed to be released by 2.8.0 back in 2019.
As this now changed to a new minor version in 2021 :wink:, this PR adjusts the Version reference to avoid confusion.
=> feat(flag): update version reference

server/documents/modules/dropdown.html.eco
Changed default value for dropdowns `forceSelection` setting as of https://github.com/fomantic/Fomantic-UI/pull/1747
=> feat(dropdown): new default value for forceSelection

server/files/javascript/icon.js
The icon page does not work on IE11 because of used arrow functions. I changed this to traditional ES5 functions, and the page works again.
=> fix(icon): arrow functions do not work on IE11

server/documents/modules/dropdown.html.eco
Changed default value for dropdowns `fullTextSearch` setting as of https://github.com/fomantic/Fomantic-UI/pull/2042
=> feat(form): new default value for fulltextsearch

server/documents/modules/dropdown.html.eco
Changed default value for dropdowns `showOnFocus` setting as of https://github.com/fomantic/Fomantic-UI/pull/2044
=> feat(dropdown): new default value for showonfocus

server/documents/collections/form.html.eco
This PR adds a hint to explain the developer any `message` in a form, which is supposed to be display any time regardless of the form state, should have the `visible` class.
https://github.com/fomantic/Fomantic-UI/issues/1196
=> feat(form): hint to always show messages

server/partials/library-javascript.html.eco
We don't need the cookie plugin anymore and already removed it from the nag code and also from the folder.
But we forgot to remove the link in the webpages, so everytime a page loads it throws a 404 error)
=> fix(chore): remove cookie link

server/documents/elements/emoji.html.eco, server/files/javascript/emoji.js
The section links on the right side are not working for emoji categories.
The emoji list is generated by javascript. However, this was done after the document was loaded and AFTER the central docs.js was auto generating the achor links. This PR changes the order of the execution, so by the time the anchor link routine seeks for proper segments, those are available at runtime now.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/128833083-1b442250-f7a6-4689-af3f-0413e9d05a03.png)|![image](https://user-images.githubusercontent.com/18379884/128832889-532edac9-c2e9-44c7-ad16-19cce760a580.png)|
=> fix(emoji): fix anchor link generation

server/documents/modules/modal.html.eco
This PR makes clear that each action buttons created out of a config setting will close the modal by default and the developer has to return false to prevent that
=> fix(modal): hint for autoclosing on actions

server/documents/behaviors/form.html.eco
Changed default value for forms `errorFocus` setting as of https://github.com/fomantic/Fomantic-UI/pull/2041
=> feat(form): new default value for errorFocus

server/documents/modules/modal.html.eco
This PR adds an info about how to deal with action buttons having any approve/deny classnames set as of https://github.com/fomantic/Fomantic-UI/pull/2108
=> fix(modal): info about approve deny classes in actions

server/documents/modules/toast.html.eco
Just as in #311 for modal, this PR adds an info about how to deal with action buttons in toasts having any approve/deny classnames set as of https://github.com/fomantic/Fomantic-UI/pull/2112 for the toast module as the logic is identical to modal
=> fix(toast): info about approve deny classes in actions

server/documents/behaviors/api.html.eco
This PR removed the hint for the serialObject dependency as we have removed and integrated it directly by 
https://github.com/fomantic/Fomantic-UI/pull/2047
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/18379884/135750948-e2fff9cf-c95d-4a48-970a-d0ed2a86ef1f.png)|![image](https://user-images.githubusercontent.com/18379884/135750953-5db45051-1843-4440-a5e6-f52251f4a15d.png)|
=> fix(api): remove dependency hint as serializeform is inbuild now

server/files/javascript/icon.js, server/files/stylesheets/docs.css
Improve the search of the icon page when using native browser
find in page function while keeping performance at best.
This new method hides the individual icons rather then the whole
category however it keeps the icon name visible. Once the icon itself
is within view bounds it will then show it. Using this method the
browser will still search the icon names since the text is still on
show.
Fixes #316
=> fix(icons): improve icon page search

server/documents/collections/form.html.eco
On a 100% OS scale (and 2k resolution) a dropdown menu inside a`fields` which itself is inside a `field` container is sometimes displayd wrong by 1px  . This is because the browser tries to calculate a 100% width for the menu out of its parent containers.
If you have an OS scale of browser zoom or  > 100% the issue is not happening....
- Scale OS to 100%
- Keep your browser zoom to 100% as well
- Open the month dropdown next to the CVC input field in the "shipping information" form
https://fomantic-ui.com/collections/form.html#form
if you compare to the country dropdown, which is only inside a normal `field` the issue is not happening, so this is a special case for the given example only
=> fix(form): fix dropdown width inside fields inside form field

server/documents/introduction/getting-started.html.eco
The docs site is already using latest jquery 3.6.0.
However, the references in CDN link examples are still referring to 3.3.1 which this PR now corrects
=> feat(gettingstarted): update jquery version reference

server/documents/modules/tab.html.eco, server/files/javascript/tab.js, server/files/stylesheets/docs.css
Added example for `inverted` and `bottom attached menu` as of https://github.com/fomantic/Fomantic-UI/pull/2082
I also added a hint to wrap a tabular menu havont attached tab segments as of https://github.com/fomantic/Fomantic-UI/pull/1480
=> feat(tab): added inverted example and attached hint

server/documents/views/card.html.eco
[Card buttons](https://fomantic-ui.com/views/card.html#buttons), supposed to be shown at top or button, do not need the `attached` class. Infact adding that class will make the button appear overlaying the card to the sides.
https://github.com/fomantic/Fomantic-UI/issues/1865
=> fix(card): buttons in card dont need attached class

server/documents/modules/dropdown.html.eco
This adds a bit more of clarifications how to use the complex dropdown behaviors.
It also reflects the changes from https://github.com/fomantic/Fomantic-UI/pull/2326 , so the internally used arguments are not needed to be provided.
I also added `get values`, to describe the difference to `get value` between values in div (string) or select (array) dropdowns
#245
=> feat(dropdown): make behavior usage more clear

server/documents/elements/emoji.html.eco
By fixing the emojie/flag default line height by https://github.com/fomantic/Fomantic-UI/pull/2337 some emoji examples appear too small
=> fix(emoji): show some features in higher size

server/documents/modules/dropdown.html.eco
It is clearer that there is an example of how values ​​structure.
Without example I thought that this is the way to change values (like `setup menu(values)`):
<kbd>Not working</kbd>
```
$('.ui.dropdown').dropdown('change values', {
values: [
{
name: 'Male (Not working example)',
value: 'male',
},
]
});
```
<kbd>working</kbd>
```
$('.ui.dropdown').dropdown('change values', [
{
name: 'Male',
value: 'male',
},
{
name: 'Female',
value: 'female',
}
]);
```
=> feat(dropdown): add values examples for change values behavior

server/documents/modules/calendar.html.eco, server/files/javascript/calendar.js
Added new token format example and adjusted related other examples like 24h format as of https://github.com/fomantic/Fomantic-UI/pull/2324
=> feat(calendar): token string format examples

server/documents/collections/table.html.eco
Added info about colored and marked combi classname order support as of https://github.com/fomantic/Fomantic-UI/pull/2377
=> feat(table): colored and marked

server/documents/elements/container.html.eco
Added infos about the `wide` variant for container as of https://github.com/fomantic/Fomantic-UI/pull/2256
=> feat(container): wide variant

server/documents/modules/accordion.html.eco, server/documents/modules/search.html.eco
The easing info was wrong or missing for search and accordion 
- accordion has a different default easing than written in the docs,
- additional link added to search
=> fix(search, accordion): fix easing info

server/documents/modules/sidebar.html.eco
The documentation still references code that was removed a long time ago.
=> refactor(sidebar): remove un-used legacy code

server/documents/modules/flyout.html.eco
Since `flyout` is a new 2.9.0 component, we should only display the short `.$` notation when creating a flyout with js properties.
=> feat(flyout): short $. notation

server/documents/modules/dropdown.html.eco, server/files/javascript/docs.js, server/partials/ui-css.html.eco, server/partials/ui-javascript.html.eco
Added actionable example as of https://github.com/fomantic/Fomantic-UI/pull/1854
I also added missing documented settings and fixed docpads "doesn't do anything" when using an eco template which contains no template scripts
=> feat(dropdown): actionable example and missing settings

server/documents/introduction/getting-started.html.eco
We already updates jquery internally for the docs to 3.6.1 by #363 , so the example links should also point to 3.6.1
=> fix(chore): update links to latest jquery 3.6.1

server/documents/elements/emoji.html.eco, server/documents/elements/flag.html.eco, server/documents/elements/icon.html.eco, server/documents/introduction/build-tools.html.eco
Added info about colors.less, variation.variables and hint how to reduce icon/emoji/flag via variable changes
=> feat(chore): global css reduce infos

README.md, server/documents/elements/button.html.eco, server/files/javascript/docs.js, server/files/javascript/visibility.js
- Whenever a link had a given anchor, but the anchor wasn't inside the first tab, the anchor was not scrolled. I now fixed that, so the tab where the anchor belongs to is set to active prior to creating the tabs.
- visiblity has a unlogical and syntax error not respecting correct variable types when switching to the usage tab resulting in console errors
-  added the labeled icon loading button example from sui 2.5.0 (we fixed the CSS already  2 years ago, but did not add an example
- removed unused code
- added version info for docpad (partly adopted the readme changes from SUI 2.5.0)
=> fix(chore): anchors in hidden tabs, js fixes

server/documents/introduction/getting-started.html.eco
Recently added Fomantic UI to one of my projects. I believe this is the directory to be accessed for the build command, assuming the directory was not changed in `semantic.json`. I think the `node_modules/fomantic-ui` directory would work as well, but if you installed Fomantic using `npx gulp install`, you might want to start running the build command from `semantic/` directory instead, especially if you want to make changes to it in the future.
=> fix(build): clarify directory used for build

server/documents/modules/calendar.html.eco
On long date+time strings the default input field isnt wide enough.
#394
=> fix(calendar): wide input field to cover long datetime strings

server/documents/modules/modal.html.eco
Made it more clear how action buttons do auto close the modal.
Also fixed the display of selectors (`&gt;` instead of >)
https://github.com/fomantic/Fomantic-UI/issues/1404
=> fix(modal): clarify action button closing

server/documents/introduction/new.html.eco, yarn.lock
Fixes json5 https://nvd.nist.gov/vuln/detail/CVE-2022-46175
=> fix(dependencies): yarn update fix cve-2022-46175

server/partials/demo-flyout.html
The multi flyout position example was not able to be closed on mobile, because the dimmer is not visible anymore.
This PR simply adds close icons to each flyout, so it's usable again
#388
=> fix(flyout): add close icons

server/documents/modules/popup.html.eco, server/files/javascript/popup.js
Added examples for 
- new multiline as of https://github.com/fomantic/Fomantic-UI/pull/2556
- colored popups/tooltips as of https://github.com/fomantic/Fomantic-UI/pull/2553
=> feat(popup): colored and multiline examples

server/documents/modules/checkbox.html.eco, server/files/stylesheets/docs.css
The checkbox supports dedicated sizing outside of a form, which was missing documentation
=> feat(checkbox): add sizes variants

server/documents/collections/grid.html.eco, server/documents/collections/menu.html.eco, server/documents/elements/segment.html.eco, server/documents/modules/dropdown.html.eco
Adjusts the left/right attached examples in favor of the dedicated `seamless` variant as of https://github.com/fomantic/Fomantic-UI/pull/2691
=> feat(segment): seamless variant

server/documents/elements/segment.html.eco
Making `horizontal stackable` deprecated and replaced by `horizontal wrapping` segment as of https://github.com/fomantic/Fomantic-UI/pull/2694
=> feat(segment): wrapping alias

server/documents/modules/popup.html.eco, server/documents/modules/slider.html.eco, server/files/javascript/slider.js
Info about restrictedLabels, minRange, maxRange, tooltip as of https://github.com/fomantic/Fomantic-UI/pull/2726
Also added new `visible` tooltip variation
=> feat(slider): minRange, maxRange, restrictedLabels, tooltip

server/documents/introduction/build-tools.html.eco
More info about how to reduce colors as this can be simply done inside variation.variables.
Otherwise a build error will occur when variation.variables still refers to some color which does not exist inside colors.less anymore
That said, i also move the section about variation.variables before the colors.less section so people know about the variation.variables file before
=> feat(chore): color reducing via variation.variables instead of colors

server/documents/modules/dropdown.html.eco, server/files/javascript/dropdown.js
Added `keepSearchTerm` example and removed unused glyphWidth setting as of https://github.com/fomantic/Fomantic-UI/pull/2743
=> feat(dropdown): keepsearchterm example

server/documents/behaviors/form.html.eco, server/files/javascript/validate-form.js
Added an example to only use native browser validation as of https://github.com/fomantic/Fomantic-UI/pull/2751
=> feat(form): native browser validation example

server/documents/collections/table.html.eco, server/documents/elements/container.html.eco, server/documents/elements/segment.html.eco, server/documents/modules/dropdown.html.eco, server/documents/modules/flyout.html.eco, server/documents/modules/modal.html.eco, server/documents/modules/search.html.eco
- added resizable infos as of https://github.com/fomantic/Fomantic-UI/pull/2748
- added missing scrolling content example for flyout
- fixed some typos
=> feat(multiple): resizable info, scrolling content missing and typo fixes

server/documents/modules/dropdown.html.eco
The "text label" example had the code view icon disabled
@ihorvyshniakov This fixes your SUI issue (i cannot comment there)
https://github.com/Semantic-Org/Semantic-UI/issues/7114
=> fix(dropdown): enable codeview for text label example

server/files/javascript/docs.js, server/files/stylesheets/docs.css
In case a Heading inside examples already got a link, the automatic anchor link wrapper would eliminate the functionality of the existing link. This happens on the homepage examples where the Headings are supposed to link to the related component website but instead a click on them does nothing as the wrapped anchor link prevents that.
So, the linkify anchor generation should only happen when the heading does not already contain a link, which this PR fixes
=> fix(chore): dont linkify existing links in headers

server/documents/behaviors/form.html.eco
Some settings were missing or had oldfashioned values
=> fix(formvalidation): update/add missing settings

server/documents/modules/flyout.html.eco, server/documents/modules/sidebar.html.eco
Removed unused/non existent ios settings as of https://github.com/fomantic/Fomantic-UI/pull/2897
The mentioned ios css settings were already removed in SUI 2.1.11 by https://github.com/Semantic-Org/Semantic-UI/commit/da0aff070a05ab2c12a603c9c5db01b9208e9400, so the ios information example is just wrong , becaus the mentioned selector is not part of FUI/SUI anymore since 2017 (!)
=> fix(sidebar,flyout): remove unused ios settings

server/documents/modules/dropdown.html.eco
Added `unlimited` example for dropdown as of https://github.com/fomantic/Fomantic-UI/pull/2883
=> feat(dropdown): unlimited menu height example

server/documents/behaviors/form.html.eco, server/documents/collections/grid.html.eco, server/files/javascript/docs.js, server/files/javascript/home.js, server/files/javascript/new.js, server/files/javascript/validate-form.js, server/files/stylesheets/docs.css
- Added new `notEmpty` rule as of https://github.com/fomantic/Fomantic-UI/pull/2949
- marked the `empty` rule as deprecated
- Added a general deprecation labeling system via `data-deprecated` for `h4` and `tr` tags
=> feat(form): notempty rule and deprecation labeling

server/documents/elements/label.html.eco
Added info and example about label groups having a vertical margin
=> feat(label): info about vertical margin in groups

server/files/javascript/calendar.js
The enabledDates Example was not working because the running Js code had different values than the example on the page.
#490
=> fix(calendar): enableddates example was not working

server/documents/introduction/getting-started.html.eco
Added info about gulp install when updating fomantic (same as for installing)
Reported in the discord general channel
=> fix(build): added gulp install info when updating

server/documents/behaviors/form.html.eco
info about thisArg for prompt function call as of https://github.com/fomantic/Fomantic-UI/pull/2942
=> feat(form): info about thisArg for prompt function call

server/documents/modules/dropdown.html.eco, server/documents/modules/embed.html.eco, server/documents/modules/search.html.eco, server/documents/modules/toast.html.eco
info about new `alt` settings for dropdown, search and toast as of https://github.com/fomantic/Fomantic-UI/pull/3011 and https://github.com/fomantic/Fomantic-UI/pull/2809
=> feat(a11y): optional alt setting for embed, toast, dropdown and search

server/documents/modules/dropdown.html.eco, server/documents/modules/search.html.eco
Examples and info about `highlightMatches` and `ignoreSearchCase` (for search) setting as of https://github.com/fomantic/Fomantic-UI/pull/2963
=> feat(dropdown, search): highlightMatches info

server/partials/less.html.eco
polyfill.io is out of service. We still need this as long as we support IE11 (until 2.10), as LESS uses JS functionality which does not work in IE11. ( See #308  )
This PR replaces the original URL by a cloudflare link as they mirrored the same functionality some time ago.
https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet
https://github.com/fomantic/Fomantic-UI/discussions/3084
=> fix(less): use cloudflare polyfill mirror

server/partials/footer.html
=> fix(footer): x was formerly twitter

server/files/javascript/emoji_strategy.js, server/files/javascript/flag.js
According to https://en.wikipedia.org/wiki/North_Macedonia , the related country flags name need correction
https://github.com/Semantic-Org/Semantic-UI/issues/7143
=> fix(flag): new name of north macedonia

server/documents/behaviors/api.html.eco, server/documents/behaviors/form.html.eco, server/documents/behaviors/state.html.eco, server/documents/behaviors/visibility.html.eco, server/documents/collections/form.html.eco, server/documents/index.html.eco, server/documents/introduction/new.html.eco, server/documents/modules/accordion.html.eco, server/documents/modules/calendar.html.eco, server/documents/modules/checkbox.html.eco, server/documents/modules/dimmer.html.eco, server/documents/modules/dropdown.html.eco, server/documents/modules/embed.html.eco, server/documents/modules/flyout.html.eco, server/documents/modules/modal.html.eco, server/documents/modules/nag.html.eco, server/documents/modules/popup.html.eco, server/documents/modules/progress.html.eco, server/documents/modules/rating.html.eco, server/documents/modules/search.html.eco, server/documents/modules/sidebar.html.eco, server/documents/modules/slider.html.eco, server/documents/modules/toast.html.eco, server/documents/modules/transition.html.eco, server/documents/views/card.html.eco, server/files/javascript/docs.js
This PR sets the default code formatting to javascript instead of HTML for all demo or evaluated code fragments.
This reduces code and fixes all non correctly styled JS code
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/6380e8cf-d258-4072-bf28-ee95e77cd751)|![image](https://github.com/user-attachments/assets/92e95af7-5232-4e44-923d-fe033c9b6cc7)|
=> fix(chore): simplify js formatting

server/documents/introduction/getting-started.html.eco
Little hint that the SASS repo is not maintained by us and that is also is a ruby gem (instead of a complete themable sass conversion, which people might believe in)
=> feat(chore): SASS is third party

server/documents/modules/calendar.html.eco
The `on` setting for calendar is forwarded to the internal popup usage. This wasnt clear, so i copied the relevant setting description from popup to calender  as well
=> feat(calendar): detailed on setting

server/documents/modules/calendar.html.eco
Improve the documentation for the original usage, emphasizing that a JavaScript Date object was being returned by the relevant Calendar Behaviors.
Also, document the new Behaviors with the optional `format` parameter.
Documents: https://github.com/fomantic/Fomantic-UI/pull/3141
=> feat(calendar): document usage scope of format tokens

server/documents/elements/divider.html.eco
divider inside stackable grids finally got a fix by https://github.com/fomantic/Fomantic-UI/pull/3170
However, the divider needs to be placed between the columns where it should be shown.
=> fix(divider): vertical variant in stackable grid fix

server/documents/behaviors/form.html.eco, server/documents/collections/form.html.eco, server/documents/elements/divider.html.eco, server/documents/elements/input.html.eco, server/documents/index.html.eco, server/documents/introduction/new.html.eco, server/documents/modules/calendar.html.eco, server/documents/views/card.html.eco
An icon inside an input gets full opacity on focus. To accomplish this, the icon needs to exist after the input node, so this PR adjusts this wherever the docs didnt do that before
=> fix(input): move left icon to support icon opacity

server/documents/modules/dropdown.html.eco
Enhanced the height examples using `unlimited` when submenus are used inside a selection dropdown which was visually adjusted by https://github.com/fomantic/Fomantic-UI/pull/3163^
=> feat(dropdown): unlimited height with submenu example
