fomantic/Fomantic-UI-Docs

- server/documents/modules/dropdown.html.eco
Corrected typo in Usage tab for dropdown
> docs(dropdown): Custom action in usage tab

- server/documents/modules/dropdown.html.eco
> docs(dropdown): Extend sortSelect option explanation

- server/documents/modules/rating.html.eco
Following hammy2899/Fomantic-UI#76. Just add the for disabled rating trough class
> Add documentation for disabled rating trough class

- server/documents/modules/calendar.html.eco
- server/files/javascript/calendar.js
- server/files/javascript/docs.js
- server/layouts/basic.html.eco
- server/partials/ui-css.html.eco
- server/partials/ui-javascript.html.eco
Following hammy2899/Fomantic-UI#71.
This PR add the calendar documentation.
There's some things that aren't documented yet, the parameters functions, since i'm not sure how to display them, but most of the case are covered with this PR, so it can be merged as it.
Here are the missing documented functions:
```js
formatter: {
header: function (date, mode, settings) {
//return a string to show on the header for the given 'date' and 'mode'
},
yearHeader: function (date, settings) {
//return a string to show on the header for the given 'date' in year mode
},
monthHeader: function (date, settings) {
//return a string to show on the header for the given 'date' in month mode
},
dayHeader: function (date, settings) {
//return a string to show on the header for the given 'date' in day mode
}, …
```
> Add calendar documentation

- server/documents/elements/icon.html.eco
- server/files/javascript/icon.js
- server/files/stylesheets/docs.css
Updated the icons to FontAwesome 5.3 as per https://github.com/hammy2899/Fomantic-UI/pull/79
> Updated icon page to FontAwesome 5.3

- server/documents/modules/range.html.eco
- server/documents/modules/toast.html.eco
- server/partials/header.html.eco
- server/partials/site-menu.html.eco
Adds status label to menu and header
> add BETA status to range and toast

- server/documents/modules/toast.html.eco
Examples of new Color variants as of https://github.com/fomantic/Fomantic-UI/pull/170
> [Toast] Color Variants

- server/documents/modules/calendar.html.eco
Related to fomantic/Fomantic-UI#176.
Once this PR is merged I will delete this weird branch, and I promise I will try to make good PR's on the good branch, and on the good repository...
> feat(calendar): add disabled state doc

- server/documents/modules/toast.html.eco
Examples and Settings added according to https://github.com/fomantic/Fomantic-UI/pull/139
> [Toast] New enhancements

- server/partials/header.html.eco
Removed the Widgets.
FUI should not be related to SUI in terms of Advertising
> Removed SUI Ads widget

- server/documents/modules/dimmer.html.eco
Dimmer Examples for https://github.com/fomantic/Fomantic-UI/pull/186
> [Dimmer] Examples for partially dimmer

- server/documents/modules/calendar.html.eco
Some Calendar examples did not work (unique selector necessary). Especially the very first one :wink: 
https://github.com/fomantic/Fomantic-UI/issues/210
> [Calendar] Some Examples did not work

- server/documents/modules/calendar.html.eco
Added Example and settings description for the new `disabledDaysOfWeek` property
https://github.com/fomantic/Fomantic-UI/pull/199
> [Calendar] Added Example and settings for disabledDaysOfWeek

- server/documents/views/item.html.eco
Example for inverted item for 
https://github.com/fomantic/Fomantic-UI/pull/232
> [Item] Added Example and settings for inverted item

- server/documents/elements/button.html.eco
Added Whatsapp & Telegram Buttons to Social Example according to https://github.com/fomantic/Fomantic-UI/pull/239
> [Button] Added Whatsapp & Telegram Buttons to Social Example

- server/documents/views/statistic.html.eco
Added Example for new feature `stackable statistics` as of https://github.com/fomantic/Fomantic-UI/pull/237
> [Statistic] Stackable Example

- server/documents/modules/calendar.html.eco
Added example and settings for new feature `disabledDates` as of https://github.com/fomantic/Fomantic-UI/pull/211
> [Calendar] Example and Settings for disableddates

- server/documents/elements/label.html.eco
Examples according to https://github.com/fomantic/Fomantic-UI/pull/230
> [Label] Added examples for inverted, group, basic tag

- server/documents/behaviors/api.html.eco
Added the settings entry for option `rawResponse` as of https://github.com/fomantic/Fomantic-UI/pull/294
> [API] Settings entry for rawResponse as of FUI #294

- server/documents/modules/rating.html.eco
New rating feature examples for icons and colors according to https://github.com/fomantic/Fomantic-UI/pull/303
> [Rating] New rating feature examples for icons and colors

- server/documents/elements/text.html.eco
- server/layouts/basic.html.eco
- server/partials/ui-css.html.eco
Once https://github.com/fomantic/Fomantic-UI/pull/261 will me merged, the new text element will be available
> [Text] Docs for new text element

- server/documents/collections/form.html.eco
- server/documents/elements/button.html.eco
- server/documents/elements/input.html.eco
- server/documents/elements/loader.html.eco
- server/documents/elements/segment.html.eco
- server/documents/modules/dimmer.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/modules/search.html.eco
Added docs for https://github.com/fomantic/Fomantic-UI/pull/301
> [Loader] New Loader/loading variants

- docpad.coffee
as per https://github.com/fomantic/Fomantic-UI/pull/328
> Release 2.7.1

- server/documents/elements/list.html.eco
Follow-up of https://github.com/fomantic/Fomantic-UI/pull/355
> [List] Example of Suffixed ordered list

- server/documents/modules/transition.html.eco
Added new setting `skipInlineHidden` as of https://github.com/fomantic/Fomantic-UI/pull/357
> [Transition] Added new setting skipInlineHidden

- server/documents/elements/label.html.eco
Added examples for new aligned floating option as of https://github.com/fomantic/Fomantic-UI/pull/418
> [Label] Aligned floating label example

- server/documents/index.html.eco
- server/partials/footer.html
- The Tweet Button had V2.4 statically set. Made this dynamic to use the current deployed version-tag
- Added Link to Twitter-Account in Community-Footer
> Added Social Twitter link and made FUI Version for Tweet dynamic

- server/documents/modules/modal.html.eco
Added `scrollbarWidth` option according to https://github.com/fomantic/Fomantic-UI/pull/437
> [Modal] Added option "scrollbarWidth" to settings tab

- server/documents/modules/modal.html.eco
Added new Modal option `restoreFocus` to settings tab as of https://github.com/fomantic/Fomantic-UI/pull/433
> [Modal] Added new "restoreFocus" option

- server/documents/modules/accordion.html.eco
Add a message about initializing nested accordions
https://github.com/fomantic/Fomantic-UI/issues/254
> [Accordion] add nested initialization message

- server/documents/elements/icon.html.eco
as per https://github.com/fomantic/Fomantic-UI/pull/446
> [Icons] update icons to FontAwesome 5.7

- server/documents/introduction/getting-started.html.eco
Just fixed wrong headers and descriptions in the "Getting Started" section.
> Replaced Semantic with Fomantic

- server/documents/modules/checkbox.html.eco
- server/files/javascript/checkbox.js
Added `indeterminate toggle` example as of https://github.com/fomantic/Fomantic-UI/pull/491 and actually make them appear as such (even the normal indeterminate checkbox was not displayed correctly)
> [Checkbox] Indeterminate toggle example

- server/documents/modules/modal.html.eco
Docs for new `top aligned` and `bottom aligned` modal variants as of https://github.com/fomantic/Fomantic-UI/pull/532
> [Modal] Top and Bottom aligned Modal docs

- server/documents/modules/progress.html.eco
- server/files/javascript/progress.js
Adding example of multiple progress bars proposed in https://github.com/fomantic/Fomantic-UI/pull/582
> feat(progress): Add multiple progress examples.

- server/documents/collections/grid.html.eco
- server/documents/modules/calendar.html.eco
- server/documents/modules/checkbox.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/modules/modal.html.eco
- server/documents/modules/progress.html.eco
- server/documents/usage/theming.html.eco
- server/files/javascript/calendar.js
- server/files/javascript/checkbox.js
- server/files/javascript/progress.js
as per https://github.com/fomantic/Fomantic-UI/pull/606
> chore(release): 2.7.3

- docpad.coffee
as per https://github.com/fomantic/Fomantic-UI/pull/609
> chore(release): 2.7.4

- server/documents/modules/search.html.eco
Fixed broken Diacritics example
https://fomantic-ui.com/modules/search.html#diacritics
> [Search] Diacritics example was not working

- server/documents/collections/breadcrumb.html.eco
This PR adds the inverted variant examples as of https://github.com/fomantic/Fomantic-UI/pull/720
> feat(breadcrumb): add inverted variant example

- server/documents/elements/segment.html.eco
Added examples for `fitted`, `horizontally fitted` and `vertically fitted` as of https://github.com/fomantic/Fomantic-UI/pull/702
> feat(segment): add horizontally, vertically fitted variant examples

- server/documents/behaviors/form.html.eco
- server/files/javascript/validate-form.js
This PR adds the documentation and example for fomantic/Fomantic-UI#661.
[![7296328d2e36ce353e53beb4db68bb77.png](http://tof.cx/images/2019/04/25/7296328d2e36ce353e53beb4db68bb77.png)](http://tof.cx/image/EGqmi)
> feat(form): add dirty/clean state example and documentation

- server/documents/index.html.eco
- server/files/stylesheets/docs.css
- server/layouts/homepage.html.eco
Add a search box to the index page so users can search the docs.
Search provided by Algolia 🎉
> feat(search): add a search to the index page

- server/documents/elements/icon.html.eco
Updated FA icons from 5.7.0 to 5.8.2
as per https://github.com/fomantic/Fomantic-UI/pull/730
> feat(icons): update to FA 5.8.2

- server/documents/behaviors/form.html.eco
- server/documents/collections/form.html.eco
- server/files/javascript/form.js
- server/files/javascript/validate-form.js
This PR adds documentation for the date field in forms, and explain how to choose the value that you want to grab for this field.
> feat(form): add date field and date handling examples in validation

- server/documents/introduction/new.html.eco
- server/files/javascript/new.js
There are some features added in minor version of v2.7.
This PR adds some newly-added remarkable features  to "New in 2.7", so users who visited the page can glance features at once.
> feat(*): add remarkable feature added in 2.7.1 and later

- server/documents/modules/checkbox.html.eco
Added new settings option `enableEnterKey` as of https://github.com/fomantic/Fomantic-UI/pull/824
> feat(checkbox): docs for new setting enableEnterKey

- server/documents/modules/popup.html.eco
Some popup default settings did not match the current codebase.
Based on https://github.com/Semantic-Org/Semantic-UI-Docs/issues/420 and added more missing/wrong settings
Thanks to @TivoSoho
> fix(popup): Fixed default values and missing content.

- server/documents/behaviors/form.html.eco
It was hard for me to find out how to manually add errors to the form using form validation. I think rewording it like this makes it a bit clearer for the next user
> Better description for add errors

- server/documents/modules/dropdown.html.eco
Added examples for the new possibility to add image and/or icon settings in a JSON response or value key according to https://github.com/fomantic/Fomantic-UI/pull/875
> [Dropdown] Explanation and examples of dynamic image and icon values

- server/documents/collections/table.html.eco
colored state and colored variations shared the same id anchor. This PR makes each section unique
#142
> fix(table): Make colored state a unique section id

- server/documents/behaviors/form.html.eco
Added new changes as of https://github.com/fomantic/Fomantic-UI/pull/866 and also changes wrong (copy/paste) settings which are either missing or not even available in the code at all
#140
> [Form Validation] Adjusted new , missing or even wrong settings

- server/documents/modules/popup.html.eco
Added new setting `forcePosition` according to https://github.com/fomantic/Fomantic-UI/pull/880
> [Popup] Added new forcePosition setting

- server/documents/modules/slider.html.eco
Added relevant behaviors to the docs
https://github.com/fomantic/Fomantic-UI/issues/552
> feat(slider): add relevant behaviors

- server/documents/modules/dropdown.html.eco
Added information about the newly added `ignoreSearchCase` option for dropdowns.
https://github.com/fomantic/Fomantic-UI/pull/1101/files
> feat(dropdown): add information about ignoreSearchCase

- server/documents/modules/slider.html.eco
Adds the option preventCrossover to the slider documentation.
see fomantic/Fomantic-UI#1021
> feat(slider): add preventCrossover option

- server/files/javascript/library/jquery.js
Simple update of jQuery to latest version (`.css` method only supports setting css variables in `^3.2.0`)
> build(deps): update jquery to 3.4.1

- server/documents/collections/table.html.eco
Added an example for the new `marked` feature to table rows or cells 
https://github.com/fomantic/Fomantic-UI/pull/1051
https://github.com/fomantic/Fomantic-UI/pull/1049
> [Table] Marked rows or cells example

- server/documents/modules/progress.html.eco
Added the new `keepState` parameter to the appropriate behaviors according to https://github.com/fomantic/Fomantic-UI/pull/1080
> [Progress] new keepState Parameter added

- server/documents/elements/icon.html.eco
Update icons to FontAwesome 5.11.2 as per https://github.com/fomantic/Fomantic-UI/pull/1148
> feat(icons): update icons to FA 5.11.2

- server/documents/modules/dropdown.html.eco
Added parameters to prevent the change trigger according to https://github.com/fomantic/Fomantic-UI/pull/1092
> [Dropdown] preventing change trigger option explained

- server/documents/modules/dropdown.html.eco
Added parameter descriptions to show and hide behaviors 
https://github.com/fomantic/Fomantic-UI/pull/1052
https://github.com/fomantic/Fomantic-UI/pull/1095
> [Dropdown] show and hide behavior parameters explanation

- server/documents/collections/form.html.eco
Docs for https://github.com/fomantic/Fomantic-UI/pull/1098
* Add info state to form
* Add info, warning and success states to field
> feat(form): Generalize form states

- server/documents/elements/emoji.html.eco
- server/documents/usage/theming.html.eco
- server/files/javascript/emoji.js
- server/files/javascript/emoji_strategy.js
- server/files/stylesheets/docs.css
- server/layouts/basic.html.eco
- server/partials/ui-css.html.eco
Docs page for Emojis  as of https://github.com/fomantic/Fomantic-UI/pull/326
> feat(emoji): add docs page for emoji component

- server/documents/modules/toast.html.eco
- server/files/javascript/toast.js
Examples and feature documentation for the new toast features as of https://github.com/fomantic/Fomantic-UI/pull/1129
> feat(toast): add new feature examples and updates settings documentation

- server/documents/introduction/build-tools.html.eco
Update `components` section in 
https://fomantic-ui.com/introduction/build-tools.html#semanticjson
So users can exclude/include newer components on their custom builds.
> feat(build-tools): add missing components

- server/documents/elements/emoji.html.eco
- server/files/javascript/emoji.js
Because of the autosizing fix , the docs needed to be slightly adjusted
https://github.com/fomantic/Fomantic-UI/pull/1175
> feat(emoji): adjusted docs to match autosizing emojis

- server/documents/behaviors/form.html.eco
Settings info for required fields as of https://github.com/fomantic/Fomantic-UI/pull/1244
> feat(form): added settings info for required fields

- server/documents/collections/table.html.eco
Added `rowspanned` example as of https://github.com/fomantic/Fomantic-UI/pull/1334
> feat(table): rowspanned example

- server/documents/elements/step.html.eco
Added an example for the new `right vertical steps` variant as of https://github.com/fomantic/Fomantic-UI/pull/1426
> [Steps] Added an example for new right vertical steps variant

- server/documents/modules/search.html.eco
Examples of scrolling and height variations of search.
Enhancement PR for search module: [https://github.com/fomantic/Fomantic-UI/pull/1350](https://github.com/fomantic/Fomantic-UI/pull/1350)
> feat(search): example of scrolling and height variations of search.

- server/files/stylesheets/docs.css
- server/partials/footer.html
Add DigitalOcean sponsor content
> chore(footer): add do sponsor content

- server/documents/modules/tab.html.eco
Added the new option to handle the autodetection of active tab according to https://github.com/fomantic/Fomantic-UI/pull/1488
> feat(tab): added new setting for handling auto detection of active tab

- server/documents/elements/text.html.eco
Example for text state colors as of https://github.com/fomantic/Fomantic-UI/pull/1564
> feat(text): text state colors examples

- server/documents/modules/calendar.html.eco
- server/files/javascript/calendar.js
Added an example for the new `inverted` variant as of https://github.com/fomantic/Fomantic-UI/pull/1597
> [Calendar] Inverted Variant example

- server/documents/introduction/build-tools.html.eco
Update for https://github.com/fomantic/Fomantic-UI/pull/1641
> Allow specify only individuals and leave components empty

- server/documents/modules/dropdown.html.eco
- server/files/javascript/dropdown.js
Added Info about the new `scrollhint` class as of https://github.com/fomantic/Fomantic-UI/pull/1651
> [Dropdown] Scrollhint infos

- server/documents/modules/checkbox.html.eco
Added `right aligned` examples as of https://github.com/fomantic/Fomantic-UI/pull/1670
> [Checkbox] Right aligned examples

- server/documents/modules/dropdown.html.eco
Added the `displayType` setting as of https://github.com/fomantic/Fomantic-UI/pull/1672
> [Dropdown] added displaytype setting

- server/documents/modules/dropdown.html.eco
Added the `preventChangeTrigger` parameter for the `set selected` behavior as of fomantic/Fomantic-UI#1683
> feat(dropdown): add the `preventChangeTrigger` parameter for the `set selected` behavior

- server/documents/behaviors/form.html.eco
Adds 'set optional' to the table of behaviors
https://github.com/fomantic/Fomantic-UI/pull/1695
> feat(form): set optional behavior

- server/documents/modules/progress.html.eco
Added `right aligned progress` example as of https://github.com/fomantic/Fomantic-UI/pull/1704
> [Progress] Right Aligned example

- server/documents/elements/button.html.eco
Added `stackable` example as of https://github.com/fomantic/Fomantic-UI/pull/1709
> feat(button): added stackable group variant

- server/documents/behaviors/form.html.eco
Added `errorFocus` setting as of https://github.com/fomantic/Fomantic-UI/pull/1713
> feat(form): added errorfocus setting

- server/documents/introduction/advanced-usage.html.eco
Fomantic has its own LESS repo ;)
> fix(usage): fomantic has its own less repo

- server/documents/elements/emoji.html.eco
> fix(emoji): typo correction

- server/documents/modules/slider.html.eco
Added new option `fireChange`  as of  https://github.com/fomantic/Fomantic-UI/pull/1751
> feat(slider): new option fireChange

- server/documents/modules/dropdown.html.eco
Example for `read-only` dropdown variant as of https://github.com/fomantic/Fomantic-UI/pull/1806
> feat(dropdown): read-only state example

- server/documents/modules/dropdown.html.eco
Added submenu example by values object as of https://github.com/fomantic/Fomantic-UI/pull/1821
> feat(dropdown): submenu support in values example

- server/documents/modules/nag.html.eco
- server/files/javascript/nag.js
Refactored the `nag` module site to make use of the new features as of 
https://github.com/fomantic/Fomantic-UI/pull/1795 and
https://github.com/fomantic/Fomantic-UI/pull/1823
> feat(nag): refactored nag site

- server/documents/elements/placeholder.html.eco
> fix(placeholder): splace should be 'a place'

- server/documents/modules/dropdown.html.eco
Added info about the new `onSearch` callback as of https://github.com/fomantic/Fomantic-UI/pull/1853
> feat(dropdown): onsearch behavior setting

- server/documents/modules/dimmer.html.eco
Optional individual show/hide methods as of https://github.com/fomantic/Fomantic-UI/pull/1867
> feat(dimmer): optional show/hide transition methods

- server/documents/behaviors/api.html.eco
- server/documents/behaviors/form.html.eco
- server/documents/behaviors/state.html.eco
- server/documents/behaviors/visibility.html.eco
- `behaviors/api`
- `behaviors/form`
- `behaviors/state`
- `behaviors/visibility`
> chore(behaviors): fix typo

- server/documents/collections/form.html.eco
- server/documents/collections/menu.html.eco
- `collections/form`
- `collections/menu`
> chore(collections): fix typo

- server/documents/introduction/build-tools.html.eco
- server/documents/introduction/getting-started.html.eco
- server/documents/introduction/new.html.eco
- `introduction/build-tools`
- `introduction/getting-started`
- `introduction/new`
> chore(introduction): fix typo

- server/documents/views/comment.html.eco
> chore(views): fix typo

- server/documents/modules/slider.html.eco
> fix(slider): fix invalid html class

- server/documents/introduction/getting-started.html.eco
fix document with issue #1911 [build] 'npm install fomantic-ui' fails
issue #1911: https://github.com/fomantic/Fomantic-UI/issues/1911#issue-828473251
solution: https://github.com/fomantic/Fomantic-UI/issues/1911#issuecomment-796848505
npm install --ignore-scripts fomantic-ui
cd node_modules/fomantic-ui
npx gulp install
npx gulp build
> fix(build): improved install instructions

- server/documents/elements/input.html.eco
Added 2 examples for labeled input dropdowns as of https://github.com/fomantic/Fomantic-UI/pull/1669
> feat(input): added examples for labeled dropdown

- server/documents/collections/grid.html.eco
- server/documents/elements/rail.html.eco
- server/documents/modules/embed.html.eco
- server/documents/modules/popup.html.eco
> fix(all): spelling fixes

- server/documents/modules/nag.html.eco
- Capitalize the 'I' pronoun in nag examples
- Fix some repetition typos
> fix(nag): typos

- server/documents/modules/toast.html.eco
Info about new possible `centered` positon as of https://github.com/fomantic/Fomantic-UI/pull/2006
> feat(toast): new centered position

- server/documents/elements/emoji.html.eco
- server/documents/modules/slider.html.eco
- server/documents/modules/toast.html.eco
Toast, Slider and Emoji are not new anymore. So i removed the "NEW" Status flag from those components.
> feat(chore): remove "new" status from toast, slider, emoji

- server/documents/collections/table.html.eco
- server/documents/elements/list.html.eco
- server/documents/introduction/advanced-usage.html.eco
- server/documents/introduction/new.html.eco
just some changes to the fomantic domain
> fix(chore): changes to fomantic domain

- server/documents/modules/calendar.html.eco
Added missing settings or callback properties
> fix(calendar): missing settings properties

- server/documents/collections/menu.html.eco
Added examples of new `centered` variant as of https://github.com/fomantic/Fomantic-UI/pull/2083
> feat(menu): centered variant

- server/documents/modules/tab.html.eco
Added info about new acllback `onBeforeChange` as of https://github.com/fomantic/Fomantic-UI/pull/2164
> feat(tab): new callback onbeforechange

- server/documents/modules/dimmer.html.eco
Added new callbacks `onVisible` and `onHidden` as of https://github.com/fomantic/Fomantic-UI/pull/2003
> feat(dimmer): new callback onvisible onhidden

- server/documents/index.html.eco
- server/files/javascript/docs.js
- server/files/stylesheets/docs.css
- server/partials/header.html.eco
This PR re-adds the twitter and github star button to the top of each component again.
The tweet button now points to the related page where it was clicked and 
I also removed unsed ads code
> feat(chore): reimplement twitter and github buttons

- server/documents/elements/icon.html.eco
Font Awesome update as of https://github.com/fomantic/Fomantic-UI/pull/2227
> feat(icon): font awesome 5.15.4 update

- server/documents/modules/calendar.html.eco
A bit more Detail to the `cellOptions` value of the cell formatter
https://github.com/fomantic/Fomantic-UI/issues/2224
> feat(calendar): details of celloptions in cell formatter

- server/documents/behaviors/api.html.eco
New default for apis rawResponse setting as of https://github.com/fomantic/Fomantic-UI/pull/2230
> feat(api): new default for rawresponse

- server/documents/modules/dropdown.html.eco
Added new delimiter info as of https://github.com/fomantic/Fomantic-UI/pull/2247
> fix(dropdown): added delimiter setting info and new behavior

- server/documents/elements/emoji.html.eco
- server/files/javascript/emoji.js
- server/files/javascript/emoji_strategy.js
- server/files/javascript/flag.js
- server/files/javascript/icon.js
- server/files/stylesheets/docs.css
This adds v13.1 emojis as of https://github.com/fomantic/Fomantic-UI/pull/2229 and fixes the emoji display routine
I also optimized the search box result so not only the exact term is found
> feat(emoji): v13.1 update

- server/documents/modules/modal.html.eco
The innerDimmer class is now customizable as of https://github.com/fomantic/Fomantic-UI/pull/2196
> feat(modal): innerdimmer class customizable

- server/documents/modules/calendar.html.eco
- server/files/javascript/calendar.js
Added infos and examples about `monthOffset` as of https://github.com/fomantic/Fomantic-UI/pull/2218 and `disabledHours` as of https://github.com/fomantic/Fomantic-UI/pull/2005
> feat(calendar): multimonth and disabledhours settings and examples

- server/documents/elements/button.html.eco
- server/files/stylesheets/docs.css
Added wrapping and spaced examples as of https://github.com/fomantic/Fomantic-UI/pull/2217
This PR also removes unnecessary units from 0 values in the docs css
> feat(button): wrapping and spaced examples

- server/documents/modules/accordion.html.eco
- server/files/javascript/accordion.js
Added example for `compact` and `very compact` variants as of https://github.com/fomantic/Fomantic-UI/pull/2051
Added examples for tree, pure css, basic styled and right icon accordion as of https://github.com/fomantic/Fomantic-UI/pull/2197
> feat(accordion): compact,tree,basic styled,right icon,pure css variant

- server/documents/introduction/advanced-usage.html.eco
- server/documents/introduction/build-tools.html.eco
- server/documents/introduction/getting-started.html.eco
Adjusted the install infos because the automatic script call on npm install has been removed as of https://github.com/fomantic/Fomantic-UI/pull/2272
> fix(install): adjusted info because autostart script has been removed

- server/documents/introduction/getting-started.html.eco
This upgrades the node/npm versions and adds a hint that we now support yarn
> fix(chore): upgrade node version and yarn hint

- server/documents/views/card.html.eco
Basic variant example as of https://github.com/fomantic/Fomantic-UI/pull/2311
> feat(card): basic variant examples

- server/documents/modules/accordion.html.eco
Added a hint for the new ignore selector as of https://github.com/fomantic/Fomantic-UI/pull/2296
> feat(accordion): added ignore selector hint

- server/documents/behaviors/api.html.eco
Added the possible usage of formdata for serializeForm setting as of https://github.com/fomantic/Fomantic-UI/pull/2257
> feat(api): added formdata option info

- server/documents/modules/sidebar.html.eco
Info about `overflowing` pusher option as of https://github.com/fomantic/Fomantic-UI/pull/2091
> feat(sidebar): info about overflowing pusher

- server/documents/elements/input.html.eco
Added file input examples as of https://github.com/fomantic/Fomantic-UI/pull/2145
> feat(input): file inputs

- server/documents/collections/table.html.eco
- server/documents/elements/container.html.eco
- server/documents/elements/segment.html.eco
Scrolling and stuck table variant  as well as scrolling container/segment as of 
https://github.com/fomantic/Fomantic-UI/pull/2134 and
https://github.com/fomantic/Fomantic-UI/pull/2148
> feat(table): scrolling and stuck variant

- server/documents/modules/dropdown.html.eco
This has to be reviewed and merged only if the PR which introduces scrollTopWhenTypingAdditions is merged : https://github.com/fomantic/Fomantic-UI/pull/2416
> feat(dropdown): added stuck addition variation

- server/documents/modules/accordion.html.eco
- server/documents/modules/calendar.html.eco
- server/documents/modules/checkbox.html.eco
- server/documents/modules/dimmer.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/modules/embed.html.eco
- server/documents/modules/modal.html.eco
- server/documents/modules/popup.html.eco
- server/documents/modules/progress.html.eco
- server/documents/modules/rating.html.eco
- server/documents/modules/search.html.eco
- server/documents/modules/shape.html.eco
- server/documents/modules/sidebar.html.eco
- server/documents/modules/sticky.html.eco
- server/documents/modules/tab.html.eco
- server/documents/modules/transition.html.eco
Corrected all debug settings with defaults reflecting the actual code default values
> fix(chore): corrected debug defaults

- server/documents/modules/modal.html.eco
- server/documents/modules/toast.html.eco
- server/files/javascript/docs.js
- server/files/javascript/emoji.js
- server/files/javascript/icon.js
- server/files/javascript/new.js
- server/files/javascript/toast.js
Short jQuery notation as of https://github.com/fomantic/Fomantic-UI/pull/2442
> feat(toast, modal): short $. notation

- package-lock.json
- server/documents/modules/flyout.html.eco
- server/files/javascript/docs.js
- server/files/javascript/flyout.js
- server/layouts/default.html.eco
- server/partials/demo-flyout.html
This PR add documentation for the new Flyout module. As module is actually simple, the doc is also simple for now.
> feat(flyout): flyout's module doc

- server/documents/modules/dropdown.html.eco
- server/documents/modules/search.html.eco
- server/files/javascript/docs.js
- server/files/javascript/new.js
- server/partials/examples/search.html
- server/raw/animals.json
- server/raw/categories.json
Some examples use remote urls from sui, which are not working anymore (not even on the original SUI site!)
I replaced these by either static JSON files or github api
#315
> fix(chore): replace non working remote apis

- server/documents/modules/modal.html.eco
Examples for basic header, basic actions and left actions as of https://github.com/fomantic/Fomantic-UI/pull/2403
> feat(modal): basic header, left actions

- server/documents/modules/flyout.html.eco
Added missing feature infos like config templates or pusher. (copied from modal and sidebar as the features are identical)
> feat(flyout): pusher and config templates info

- server/documents/modules/popup.html.eco
Correct logic for popups closable setting to match actual code
https://github.com/fomantic/Fomantic-UI/issues/2459
> fix(popup): clarify closable setting to match code

- server/documents/modules/flyout.html.eco
- server/documents/modules/modal.html.eco
- server/documents/modules/sidebar.html.eco
- server/partials/demo-flyout.html
Added examples for the addons from https://github.com/fomantic/Fomantic-UI/pull/2458
> feat(flyout): centered, left, basic, blurring, autoFocus,etc.

- server/documents/modules/checkbox.html.eco
Added missing `is` behaviors for checkbox
#343
> fix(checkbox): some missing behaviors

- server/files/javascript/emoji_strategy.js
- server/files/javascript/flag.js
removed some unsupported emojis and flag renaming as of https://github.com/fomantic/Fomantic-UI/pull/2466 and https://github.com/fomantic/Fomantic-UI/pull/2464
> fix(emoji): remove unsupported emojis

- server/documents/modules/dropdown.html.eco
- server/partials/examples/dropdown.html
Fixed dropdown examples having search inputs inside menu to match https://github.com/fomantic/Fomantic-UI/pull/2475
> fix(dropdown): missing search class

- server/documents/modules/tab.html.eco
- server/files/javascript/calendar.js
- server/files/javascript/docs.js
- server/files/javascript/icon.js
- server/files/javascript/new.js
- server/files/javascript/slider.js
- server/files/javascript/sticky.js
- server/files/javascript/tab.js
- server/files/javascript/visibility.js
- server/raw/metadata.json
Some fixes to avoid JS errors/debug messages
[#2478](https://github.com/fomantic/Fomantic-UI/issues/2478)
> fix(chore): cleanup js errors

- server/documents/elements/icon.html.eco
chart line change to chartline was missed in the docs
> fix(icon): missing chart line to chartline conversion

- server/documents/modules/progress.html.eco
It wasn't clear enough how the mutiple progress example using custom bar texts works, so i added the JS part for that example as well
https://github.com/fomantic/Fomantic-UI/issues/2518
> fix(progress): better understanding of multiple example

- server/documents/introduction/new.html.eco
Add info about breaking change of icon renaming
> fix(news): hint to renamed icons

- server/files/javascript/nag.js
The overlay nag examples were not closable
#400
> fix(nag): make overlay nags closable

- server/documents/modules/search.html.eco
adjusted some default settings to reflect the actual code for the search component
> fix(search): reflect current code

- server/documents/elements/label.html.eco
- Added undocumented fluid and disabled variants
- added new centered variant as of https://github.com/fomantic/Fomantic-UI/pull/2557
- moved inverted variant
> fix(label): missing fluid and disabled variant

- server/documents/collections/table.html.eco
Some variations do not work with the scrolling variant (but stuck works), so i added a hint about that.
https://github.com/fomantic/Fomantic-UI/issues/2571
> feat(table): hint when to use stuck or scrolling

- server/documents/introduction/getting-started.html.eco
Corrects jQuery version to the intended 3.6.3 version from 3.6.2
> fix(chore): update jquery example code to 3.6.3

- server/documents/introduction/build-tools.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/modules/popup.html.eco
Adjusted some links and adjusted settings according to changes in https://github.com/fomantic/Fomantic-UI/pull/2618
> fix(chore): corrected links

- server/documents/modules/search.html.eco
Added info about new `all` and `some` fullTextSearch options as of https://github.com/fomantic/Fomantic-UI/pull/2648
> feat(search): new all and some search options

- server/documents/modules/calendar.html.eco
- server/files/javascript/calendar.js
- server/files/stylesheets/calendar.css
context setting example as of https://github.com/fomantic/Fomantic-UI/pull/2548
> feat(calendar): context example

- server/documents/views/statistic.html.eco
Added fluid statistic example as of https://github.com/fomantic/Fomantic-UI/pull/2568
> feat(statistic): fluid example

- server/documents/introduction/build-tools.html.eco
New semantic.json config settings as of https://github.com/fomantic/Fomantic-UI/pull/2498 and https://github.com/fomantic/Fomantic-UI/pull/2621
> feat(build): new semantic.json settings

- server/documents/modules/transition.html.eco
Added pulsating example as of https://github.com/fomantic/Fomantic-UI/pull/2544
> feat(transition): pulsating example

- server/documents/modules/dropdown.html.eco
Info about possibility to set "false" as label transition as of https://github.com/fomantic/Fomantic-UI/pull/2647
Also adjusted some settings to reflect actual values in the code
> feat(dropdown): label.transition false info

- server/documents/behaviors/visibility.html.eco
- server/documents/iframe/fixed-menu.html
- server/documents/iframe/fixed-vertical-menu.html
- server/documents/usage/theming.html.eco
- server/files/stylesheets/docs.css
- server/files/stylesheets/home.css
- server/files/stylesheets/shape.css
- server/partials/examples/dimmer.html
- server/partials/examples/grid.html
- server/partials/examples/icon.html
- server/raw/draft/carousel.less
- server/raw/draft/extra.transitions.less
- server/raw/draft/sitemap.less
Cleanup CSS:
-  Remove vendor prefixes where not applicable anymore
- remove units on zero values
> fix(chore): remove vendor prefixes and units

- server/documents/behaviors/state.html.eco
- server/documents/modules/rating.html.eco
- server/documents/modules/search.html.eco
- server/documents/modules/sticky.html.eco
- server/documents/modules/transition.html.eco
Removed unused error messages to reflect current code as of https://github.com/fomantic/Fomantic-UI/pull/2651
> fix(chore): remove unused errors, reflect code

- server/documents/modules/transition.html.eco
missed setting and corrected defaut setting to match code
> fix(transition): missed and wrong settings

- server/documents/behaviors/form.html.eco
- server/documents/modules/sidebar.html.eco
- server/documents/modules/transition.html.eco
- server/partials/ui-css.html.eco
- server/partials/ui-javascript.html.eco
- Removed the vendor prefix check methods party not even used/existing as of https://github.com/fomantic/Fomantic-UI/pull/2662
- Some more enhancements regarding DOM tree
> fix(form): double loaded component

- server/documents/modules/modal.html.eco
- server/raw/metadata.json
- make modal buttons focussable
- Fix copy/past mistake in metadata
> feat(modal): make action buttons focusable and fix metadata

- server/documents/modules/popup.html.eco
- server/files/javascript/popup.js
Added loading examples for popup as of https://github.com/fomantic/Fomantic-UI/pull/2656
> feat(popup): loader variant

- server/documents/modules/dropdown.html.eco
Enhanced the compact examples as of https://github.com/fomantic/Fomantic-UI/pull/2678
> feat(dropdown): enhanced compact example

- server/documents/behaviors/form.html.eco
More detailed variants for `add errors` as of https://github.com/fomantic/Fomantic-UI/pull/2680
> feat(formvalidation): add error variants

- server/documents/collections/menu.html.eco
Added wrapping variants as of https://github.com/fomantic/Fomantic-UI/pull/2682
> feat(menu): wrapping variant

- server/documents/collections/grid.html.eco
- server/documents/collections/menu.html.eco
- server/documents/elements/segment.html.eco
Left/right attached variants as of https://github.com/fomantic/Fomantic-UI/pull/2683
> feat(grid, segment): left right attached variants

- server/documents/behaviors/form.html.eco
Info about new `size` rule as of https://github.com/fomantic/Fomantic-UI/pull/2688
> feat(formvalidation): size rule info

- server/documents/introduction/getting-started.html.eco
Detailed the jquery version number, as the main FUI package already defines in package.json it needs jquery 3.4+
> fix(chore): clarify jquery version

- server/documents/modules/dropdown.html.eco
Adds behavior info for "clear cache" as of  https://github.com/fomantic/Fomantic-UI/pull/2716
> feat(dropdown): clear cache method

- server/documents/modules/calendar.html.eco
Show event dates tooltip colored
> feat(calendar): event date tooltip colors

- server/documents/elements/divider.html.eco
- server/documents/elements/segment.html.eco
- server/documents/modules/search.html.eco
- server/documents/views/card.html.eco
Added missing size variants for card, divider, search and segment
> feat(multi): missing sizing variant examples

- server/documents/elements/label.html.eco
Bottom and center ribbon example as of https://github.com/fomantic/Fomantic-UI/pull/2729
> feat(label): bottom and center ribbon example

- server/documents/introduction/getting-started.html.eco
Added a general info about how FUI classname descriptions are understood and why class name order could matter in some cases
> feat(gettingstarted): info about classname order

- server/documents/modules/toast.html.eco
Some Toast settings were not documented
> feat(toast): missing settings

- server/documents/modules/search.html.eco
adjusted onResults Callback as of https://github.com/fomantic/Fomantic-UI/pull/2737
> feat(search): onResults fromCache

- server/documents/collections/menu.html.eco
Added new `equal width menu` variant as of https://github.com/fomantic/Fomantic-UI/pull/2734
> feat(menu): equal width variant

- server/files/javascript/flag.js
introduced in https://github.com/fomantic/Fomantic-UI/pull/2744
> feat(flags): add alias for czech

- server/documents/behaviors/form.html.eco
- server/documents/behaviors/visibility.html.eco
- server/documents/elements/label.html.eco
- server/documents/introduction/getting-started.html.eco
- server/documents/modules/calendar.html.eco
- server/documents/modules/dimmer.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/modules/modal.html.eco
- server/documents/modules/popup.html.eco
- server/documents/modules/search.html.eco
- server/documents/modules/sticky.html.eco
- server/documents/modules/toast.html.eco
- server/documents/views/feed.html.eco
- server/files/javascript/docs.js
- server/files/stylesheets/docs.css
improved central label generation to also fetch version infos from settings table and h2 headers
> feat(chore): improved central "newin" label generation

- server/files/javascript/flag.js
Corrects #452  as discussed in https://github.com/fomantic/Fomantic-UI/pull/2744#discussion_r1149895080
> fix(flag): czech_republic

- server/documents/elements/text.html.eco
- server/documents/index.html.eco
- server/documents/introduction/glossary.html.eco
- server/files/javascript/tab.js
Updates framework core statistics and fixed TOC creation for text and tab
> fix(text,tab,index): core infos and page fixes

- server/documents/modules/search.html.eco
- server/files/javascript/search.js
The default search fields never displayed any response
> fix(search): standard search did not work

- server/documents/behaviors/form.html.eco
- server/documents/introduction/advanced-usage.html.eco
- server/documents/introduction/build-tools.html.eco
- server/documents/modules/checkbox.html.eco
- server/documents/modules/search.html.eco
- server/documents/modules/transition.html.eco
- server/documents/usage/theming.html.eco
- server/files/javascript/docs.js
- server/files/javascript/validate-form.js
- Added info about `errorLimit` settings as of https://github.com/fomantic/Fomantic-UI/pull/2758
- Fixed form examples
- Enhanced/fixes source type display
> feat(form): errorlimit setting and fixes

- server/documents/modules/search.html.eco
Horizontal category search example as of https://github.com/fomantic/Fomantic-UI/pull/2759
> feat(search): horizontal category example

- server/documents/views/comment.html.eco
- server/documents/views/item.html.eco
Added `disabled` examples as of https://github.com/fomantic/Fomantic-UI/pull/2761
> feat(comment,item): disabled variant

- server/documents/modules/dropdown.html.eco
Added settings section for undocumented dropdown templates
https://github.com/Semantic-Org/Semantic-UI/issues/3857
> fix(dropdown): added template settings

- server/documents/elements/label.html.eco
Added a small example to use the label component for highlighting keyboard shortcuts
#358
> feat(label): keyboard shortcuts example

- server/documents/elements/emoji.html.eco
- server/files/javascript/emoji_strategy.js
Emoji unicode v14 update as of https://github.com/fomantic/Fomantic-UI/pull/2787
> feat(emoji): unicode v14.0 update

- server/documents/behaviors/form.html.eco
- server/documents/introduction/new.html.eco
Some missging /wrong information fixed
> fix(chore): wrong default setting, added missing breaking changes

- server/documents/modules/calendar.html.eco
- server/files/javascript/calendar.js
Added new `size` variations as of https://github.com/fomantic/Fomantic-UI/pull/2866
> feat(calendar): added sizes example

- server/documents/modules/accordion.html.eco
Some fixes to reflect the actual code
> fix(accordion): wrong default setting

- server/documents/views/feed.html.eco
New Feed feature examples as of https://github.com/fomantic/Fomantic-UI/pull/2745
> feat(feed): disabled, divided, ordered, connected examples

- server/documents/elements/header.html.eco
Add example for seamless top attached header.
> feat(header): seamless attached header example

- server/documents/behaviors/api.html.eco
- server/documents/behaviors/form.html.eco
- server/documents/behaviors/visibility.html.eco
- server/documents/collections/grid.html.eco
- server/documents/collections/table.html.eco
- server/documents/elements/list.html.eco
- server/documents/elements/segment.html.eco
- server/documents/modules/dropdown.html.eco
- server/documents/views/item.html.eco
- server/files/javascript/docs.js
Some cleanup
- removed dead code
- fixed word order highlighting in some cases
- fixed some typos
> fix(chore): removed dead code, typos, fixed required word order hints

- server/documents/behaviors/api.html.eco
- server/documents/behaviors/form.html.eco
- server/documents/behaviors/state.html.eco
- server/documents/behaviors/visibility.html.eco
- server/raw/metadata.json
- The hidden but always included state module was never documented, so i finally did this
- Added missing behaviors and typo to api and form
I basically took, fixed and enhanced the examples from https://github.com/Semantic-Org/Semantic-UI/issues/609#issuecomment-42430071
> fix(chore): added missing behaviors and updated state module

- server/documents/behaviors/form.html.eco
Added info about noNativeValidation Setting as of https://github.com/fomantic/Fomantic-UI/pull/2941
> feat(form): noNativeValidation setting

- server/documents/modules/dropdown.html.eco
some missing "data-since" labels
> fix(dropdown): some missing data-since properties

- server/partials/footer.html
update sponsors as of https://github.com/fomantic/Fomantic-UI/pull/3013
> fix(chore): update sponsors

- server/documents/elements/button.html.eco
Circular buttons group variation example as of https://github.com/fomantic/Fomantic-UI/pull/2946
> feat(button): circular buttons group

- server/documents/behaviors/form.html.eco
Added new ignoreMissing parameter as of https://github.com/fomantic/Fomantic-UI/pull/2901
> feat(form): new ignoreMissing parameter

- server/documents/modules/dropdown.html.eco
Added info about possible data attributes for dropdown items as of https://github.com/fomantic/Fomantic-UI/pull/3004
> feat(dropdown): custom data attributes for dropdown items

- server/documents/behaviors/form.html.eco
"Matching Fields" Header existed twice, breaking the automatic TOC links
#501
> fix(form): create unique example headers

- server/documents/modules/dropdown.html.eco
consistent parameter naming for dropdowns "onchange" third function parameter
#504
> fix(dropdown): consistent parameter naming

- server/documents/modules/progress.html.eco
`basic` variant example as of https://github.com/fomantic/Fomantic-UI/pull/3040
> feat(progress): basic progress example

- server/documents/modules/transition.html.eco
The "set looping" behavior was incorrectly listed
> fix(transition): correct looping behavior

- server/documents/modules/dropdown.html.eco
> fix(dropdown): fixed example nesting

- server/documents/elements/emoji.html.eco
- server/files/javascript/emoji_strategy.js
Updates to emoji 15.1 characters support as of https://github.com/fomantic/Fomantic-UI/pull/3086
> feat(emoji): update to emoji v15.1

- server/files/stylesheets/docs.css
- server/files/stylesheets/home.css
- server/partials/tab-header.html.eco
remove remaining dead unused carbon ads code
> feat(chore): remove unused remaining carbon ads code

- server/documents/introduction/build-tools.html.eco
Documenting: https://github.com/fomantic/Fomantic-UI/pull/3138
> feat(build): optionally include version in released filename

- server/documents/modules/search.html.eco
The template functions were missing all the existing function parameters
> fix(search): missing function parameters for templates

- server/documents/introduction/build-tools.html.eco
info about new `fileName` setting in semantic.json as of https://github.com/fomantic/Fomantic-UI/pull/3140
> feat(build): custom output filename

- server/documents/modules/dropdown.html.eco
- server/documents/modules/search.html.eco
Added clearable examples as of https://github.com/fomantic/Fomantic-UI/pull/3133
> feat(search): clearable example

- server/documents/modules/slider.html.eco
- server/files/javascript/docs.js
- server/files/javascript/slider.js
New examples for the new features as of https://github.com/fomantic/Fomantic-UI/pull/3111
> feat(slider): new feature examples

- server/files/stylesheets/docs.css
- server/layouts/default.html.eco
- server/layouts/homepage.html.eco
- server/partials/gurubase.html
Adds gurubase Ai Widget to every page for a nice AI Bot which LLM is fed by the fui website and fui github repo
> feat(chore): add gurubase ai widget

- server/documents/elements/step.html.eco
Added examples for all new features of the new `circular steps` variant as of https://github.com/fomantic/Fomantic-UI/pull/2917
> feat(step): circular variant examples

- server/files/stylesheets/docs.css
- server/partials/gurubase.html
gurubase widget needed some adjustments so the algolia widget does not get misplaced
Also added some tooltip to the new widget option
> fix(chore): adjust widget positioning
